language: php
sudo: false
dist: trusty

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_TRAVISCI="travis:phpunit"

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

before_install:
  - travis_retry composer self-update

install:
  - composer install --prefer-source --no-interaction --dev
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi

script:
  - composer phpcs
  - composer test-unit
  - composer test-integration

notifications:
    on_success: never
    on_failure: always
